spring.application.name=keepNotes
server.port=8081
spring.security.user.name = vaishnavi
spring.security.user.password = vaishnavi123
spring.web.error.include-message=always

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console